### ISSUE TITLE
🔐 SMTP allow list capture and apply

### ISSUE THREAD

**Issue by ASTRobinson** [ministryofjustice/staff-infrastructure-smtp-relay-server#20]
## User Story

As a…Cloud Ops Engineer 
I want to…  limit the range of allowed IP addresses  on the SMTP Relay server
So that… our exposure is minimal from a security aspect. 

## Value / Purpose
Align to RFC standards and improve security standards.  
Gather current devices which are relaying to define the allow unauthenticated relay. 
We can then apply this to the allow list on the SMTP config.

## Useful Contacts
Aaron Robinson
Richard Baguley
Touhid Islam

## Additional Information
RFC1918

## Definition of Done (DoD)
SMTP whitelist reviewed and minimal subnet ranges / IP addresses are applied.

**Comment by mitchdawson1982** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Cloud-Operations-Team-622a0b371800e400133bb924/issues/ministryofjustice/staff-infrastructure-smtp-relay-server/20?planning-poker) with ZenHub @ASTRobinson @bagg3rs @emileswarts @Gary-H9 @kyphutruong @moontune @mTouhid @wanieldilson

**Comment by mitchdawson1982** [comment]
The current list still contains a 10.0.0.0/8 rule but this is not the long term approach. The old loadbalancer configuration did not persist the client ip which made it impossible to see the real ip's that are using the relay. We have updated the loadbalancer terraform to persist the client ip, this will enable us to create an accurate list of ip's relaying through the server. We plan to get a snapshot of ip's from the cloudwatch logs after a period of one week and will build the ip_allowed_list from these values.
