### ISSUE TITLE
📌 Spike enable and test authentication 

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/staff-infrastructure-smtp-relay-server#32]
### User Story

As a printer 🖨️ 
I want to authenticate to SMTP if I can, or be put on an allow list if I can't
So that we improve authentication against SMTP

### Value / Purpose

- Part of Print recompete which didn't have the capability of authenticated SMTP

### Useful Contacts

Rich B, Touhid, Aaron, John D

### Definition of Done

- [ ] Tested auth and network allow
- [ ] Issues created for any additional work

**Comment by mTouhid** [comment]
Spike is complete.
Findings:
It is possible to configure postfix to work with Cyrus SASL (simple authentication) to provide some authentication model for SMTP.

recommended / tested configuration can be found here: https://github.com/ministryofjustice/staff-infrastructure-smtp-relay-server/tree/spike-postfix-cyrus-sasl/smtp--simple-authentication
